# Generated by Django 4.1 on 2022-09-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=2000)),
                ("date_published", models.DateField()),
                ("link", models.CharField(max_length=4000)),
                ("link_to_author", models.CharField(max_length=4000)),
            ],
            options={
                "verbose_name": "Хабр статьи",
                "verbose_name_plural": "Хабр статьи",
            },
        ),
    ]
