# Generated by Django 4.1 on 2022-09-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2000)),
                ('date_published', models.DateField()),
                ('link', models.CharField(max_length=4000, unique=True)),
                ('link_to_author', models.CharField(max_length=4000)),
            ],
            options={
                'verbose_name': 'Хабр статьи',
                'verbose_name_plural': 'Хабр статьи',
            },
        ),
    ]
