# Generated by Django 4.1 on 2022-09-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_habr', '0002_remove_articles_id_alter_articles_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.CharField(max_length=4000, unique=True),
        ),
    ]
